# Dependencies
highlighter:      rouge
gems: ['jekyll-paginate']
# Permalinks
permalink:        pretty

# Setup
title:            trikanto
tagline:          'A knitting blog'
description:      'Knit knit knit knit knit'
url:              http://trikanto.github.io
baseurl:          /

author:
  name:           'Bana'
  url:            https://www.instagram.com/trikanto/

paginate:         5

# Custom vars
version:          2.1.0

post:
  template: _post_template.md
  extension: md

editor: subl